add_library(libc_stdlib OBJECT
    atexit.c
    dtoa.c
    llabs.c
    mbsinit.c
    nrand48.c
    reallocr.c
    strtorQ.c
    wcstold.c
    _Exit.c
    dtoastub.c
    lldiv.c
    mbsnrtowcs.c
    on_exit.c
#    rpmatch.c # FIXME: rpmatch.c requires POSIX layer
    strtorx.c
    wcstoll.c
    __adjust.c
    atof.c
    ecvtbuf.c
    getenv.c
    mbsrtowcs.c
    on_exit_args.c
    sb_charsets.c
    strtoul.c
    wcstoll_r.c
    __atexit.c
    atoff.c
    efgcvt.c
    getenv_r.c
    lrand48.c
    mbstowcs.c
    seed48.c
    strtoull.c
    wcstombs.c
    __call_atexit.c
    atoi.c
    environ.c
    getopt.c
    malign.c
    mbstowcs_r.c
    putenv.c
    setenv.c
    strtoull_r.c
    wcstombs_r.c
    __exp10.c
    atol.c
    envlock.c
    getsubopt.3
    malignr.c
    mbtowc.c
    putenv_r.c
    setenv_r.c
    strtoumax.c
    wcstoul.c
    __ten_mu.c
    atoll.c
    eprintf.c
    getsubopt.c
    mallinfor.c
    mbtowc_r.c
    pvallocr.c
    srand48.c
    system.c
    wcstoull.c
    _mallocr.c
    btowc.c
    erand48.c
    imaxabs.c
    malloc.c
    mlock.c
    quick_exit.c
    utoa.c
    wcstoull_r.c
    a64l.c
    calloc.c
    exit.c
    imaxdiv.c
    mallocr.c
    mprec.c
    rand.c
    stdlib.tex
    valloc.c
    wcstoumax.c
    abort.c
    callocr.c
    freer.c
    itoa.c
    malloptr.c
    rand48.c
    strtod.c
    vallocr.c
    wctob.c
    abs.c
    cfreer.c
    gdtoa-dmisc.c
    jrand48.c
    mallstatsr.c
    mrand48.c
    strtodg.c
    wcrtomb.c
    wctomb.c
    aligned_alloc.c
    gdtoa-gdtoa.c
    l64a.c
    msize.c
    rand_r.c
    strtoimax.c
    wcsnrtombs.c
    wctomb_r.c
    arc4random.c
    cxa_atexit.c
    gdtoa-gethex.c
    labs.c
    mblen.c
    msizer.c
    random.c
    strtol.c
    wcsrtombs.c
    cxa_finalize.c
    gdtoa-gmisc.c
    lcong48.c
    mblen_r.c
    mstats.c
    realloc.c
    strtold.c
    wcstod.c
    arc4random_uniform.c
    div.c
    gdtoa-hexnan.c
    ldiv.c
    mbrlen.c
    mtrim.c
    reallocarray.c
    strtoll.c
    wcstoimax.c
    assert.c
    drand48.c
    gdtoa-ldtoa.c
    ldtoa.c
    mbrtowc.c
    nano-mallocr.c
    reallocf.c
    strtoll_r.c
    wcstol.c
)

target_include_directories(libc_stdlib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(libc_stdlib PRIVATE libc_includes)