add_library(utilities OBJECT
    utaddress.c
    utalloc.c
    utascii.c
    utbuffer.c
    utcache.c
    utcksum.c
    utclib.c
    utcopy.c
    utdebug.c
    utdecode.c
    utdelete.c
    uterror.c
    uteval.c
    utexcep.c
    utglobal.c
    uthex.c
    utids.c
    utinit.c
    utlock.c
    utmath.c
    utmisc.c
    utmutex.c
    utnonansi.c
    utobject.c
    utosi.c
    utownerid.c
    utpredef.c
    utprint.c
    utresdecode.c
    utresrc.c
    utstate.c
    utstring.c
    utstrsuppt.c
    utstrtoul64.c
    uttrack.c
    utuuid.c
    utxface.c
    utxferror.c
    utxfinit.c
    utxfmutex.c
    )

target_include_directories(utilities PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/../include ${DRIVER_API})