#ifndef KERNEL_DEV_TYPEDEFS_H_
#define KERNEL_DEV_TYPEDEFS_H_

#include <stdint.h>

EXPORT
typedef uint32_t IoDeviceFlags;
#define IO_DEVICE_FLAG_INITIALIZED 0x1
#define IO_DEVICE_FLAG_READY_TO_RUN 0x2
#define IO_DEVICE_FLAG_INITIALIZATION_FAILURE 0x4
#define IO_DEVICE_FLAG_BUFFERED_IO 0x1000
#define IO_DEVICE_FLAG_DIRECT_IO 0x2000
#define IO_DEVICE_FLAG_PERSISTENT 0x80000000
#define IO_DEVICE_FLAG_REMOVABLE_MEDIA 0x40000000
#define IO_DEVICE_FLAG_ENUMERATION_CAPABLE 0x20000000
#define IO_SUBDEVICE_FLAG_PERSISTENT (IO_DEVICE_FLAG_PERSISTENT)

EXPORT
typedef uint32_t IoDriverRpFlags;
#define IO_DRIVER_RP_FLAG_SYNCHRONOUS 0x01

#endif