add_library(libc_ctype OBJECT
    categories.c
    ctype_.c
    isalnum_l.c
    isalnum.c
    isalpha_l.c
    isalpha.c
    isascii_l.c
    isascii.c
    isblank_l.c
    isblank.c
    iscntrl_l.c
    iscntrl.c
    isdigit_l.c
    isdigit.c
    islower_l.c
    islower.c
    isprint_l.c
    isprint.c
    ispunct_l.c
    ispunct.c
    isspace_l.c
    isspace.c
    isupper_l.c
    isupper.c
    iswalnum_l.c
    iswalnum.c
    iswalpha_l.c
    iswalpha.c
    iswblank_l.c
    iswblank.c
    iswcntrl_l.c
    iswcntrl.c
    iswctype_l.c
    iswctype.c
    iswdigit_l.c
    iswdigit.c
    iswgraph_l.c
    iswgraph.c
    iswlower_l.c
    iswlower.c
    iswprint_l.c
    iswprint.c
    iswpunct_l.c
    iswpunct.c
    iswspace_l.c
    iswspace.c
    iswupper_l.c
    iswupper.c
    iswxdigit_l.c
    iswxdigit.c
    isxdigit_l.c
    isxdigit.c
    jp2uc.c
    toascii_l.c
    toascii.c
    tolower_l.c
    tolower.c
    toupper_l.c
    toupper.c
    towctrans_l.c
    towctrans.c
    towlower_l.c
    towlower.c
    towupper_l.c
    towupper.c
    wctrans_l.c
    wctrans.c
    wctype_l.c
    wctype.c
)

target_include_directories(libc_ctype PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(libc_ctype PRIVATE libc_includes)