add_library(libc_string OBJECT
    index.c
    rawmemchr.c
    strcpy.c
    strncmp.c
    strupr.c
    wcschr.c
    wcsncpy.c
    wmemcmp.c
    local.h
    rindex.c
    strcspn.c
    strncpy.c
    strverscmp.c
    wcscmp.c
    wcsnlen.c
    wmemcpy.c
    memccpy.c
    stpcpy.c
    strdup.c
    strndup.c
    strxfrm.c
    wcscoll.c
    wcspbrk.c
    wmemmove.c
    bcmp.c
    memchr.c
    stpncpy.c
    strdup_r.c
    strndup_r.c
    strxfrm_l.c
    wcscoll_l.c
    wcsrchr.c
    wmempcpy.c
    bcopy.c
    memcmp.c
    str-two-way.h
    strerror.c
    strnlen.c
    swab.c
    wcscpy.c
    wcsspn.c
    wmemset.c
    bzero.c
    memcpy.c
    strcasecmp.c
    strerror_r.c
    strnstr.c
    timingsafe_bcmp.c
    wcscspn.c
    wcsstr.c
    xpg_strerror_r.c
    memmem.c
    strcasecmp_l.c
    strpbrk.c
    timingsafe_memcmp.c
    wcsdup.c
    wcstok.c
    explicit_bzero.c
    memmove.c
    strcasestr.c
    strlcat.c
    strrchr.c
    u_strerr.c
    wcslcat.c
    ffsl.c
    mempcpy.c
    strcat.c
    strlcpy.c
    strsep.c
    wcslcpy.c
    wcswidth.c
    ffsll.c
    memrchr.c
    strchr.c
    strlen.c
    strsignal.c
    wcpcpy.c
    wcslen.c
    wcsxfrm.c
    fls.c
    memset.c
    strchrnul.c
    strlwr.c
    strspn.c
    wcpncpy.c
    wcsncasecmp.c
    wcsxfrm_l.c
    flsl.c
    strcmp.c
    strncasecmp.c
    strstr.c
    wcscasecmp.c
    wcsncasecmp_l.c
    wcwidth.c
    flsll.c
    strcoll.c
    strncasecmp_l.c
    strtok.c
    wcscasecmp_l.c
    wcsncat.c
    gnu_basename.c
    strcoll_l.c
    strncat.c
    strtok_r.c
    wcscat.c
    wcsncmp.c
    wmemchr.c
)

target_include_directories(libc_string PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(libc_string PRIVATE libc_includes)