set(CMAKE_SYSTEM_NAME Nabla)
set(CMAKE_C_COMPILER i686-elf-gcc)
set(CMAKE_CXX_COMPILER i686-elf-g++)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(CONFIG_USE_MULTIBOOT2 1)
set(CONFIG_LIBRARIES multiboot gcc)
set(CMAKE_ASM_NASM_COMPILER nasm)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_FLAGS "-masm=intel -ffreestanding -Wall -Wextra -Wsizeof-pointer-memaccess -Wstrict-aliasing -nostdlib -T ${CMAKE_CURRENT_SOURCE_DIR}/gcc-i686.ld -z noexecstack")
set(CMAKE_CXX_FLAGS "-masm=intel -ffreestanding -Wall -Wextra -Wsizeof-pointer-memaccess -Wstrict-aliasing -nostdlib -T ${CMAKE_CURRENT_SOURCE_DIR}/gcc-i686.ld -z noexecstack")
set(CMAKE_ASM_NASM_FLAGS "-f elf32")
set(CMAKE_C_FLAGS_DEBUG "-DDEBUG=1 -g -Og")
set(CMAKE_CXX_FLAGS_DEBUG "-DDEBUG=1 -g -Og")
set(CMAKE_ASM_NASM_FLAGS_DEBUG "-DDEBUG=1 -g -F dwarf")
set(CMAKE_C_FLAGS_RELEASE "-O3")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")