set(CMAKE_SYSTEM_NAME Nabla)
set(CMAKE_C_COMPILER i686-elf-gcc)
set(CMAKE_CXX_COMPILER i686-elf-g++)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(CONFIG_LIBRARIES gcc)
set(CMAKE_EXECUTABLE_SUFFIX .drv)
set(NABLA_DRIVER_HELPERS "${CMAKE_CURRENT_SOURCE_DIR}/gcc-helpers.cmake")
set(CMAKE_ASM_NASM_COMPILER nasm)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_FLAGS "-r -masm=intel -ffreestanding -Wall -Wextra -Wsizeof-pointer-memaccess -Wstrict-aliasing -nostdlib -z noexecstack -Wno-unused-parameter")
set(CMAKE_CXX_FLAGS "-r -masm=intel -ffreestanding -Wall -Wextra -Wsizeof-pointer-memaccess -Wstrict-aliasing -nostdlib -z noexecstack -Wno-unused-parameter")
set(CMAKE_ASM_NASM_FLAGS "-f elf32")
set(CMAKE_C_FLAGS_DEBUG "-DDEBUG=1 -g -Og")
set(CMAKE_CXX_FLAGS_DEBUG "-DDEBUG=1 -g -Og")
set(CMAKE_ASM_NASM_FLAGS_DEBUG "-DDEBUG=1 -g -F dwarf")
set(CMAKE_C_FLAGS_RELEASE "-O3")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")