#ifndef OBJECTID_H_
#define OBJECTID_H_

enum ObjectId
{
    OBJECT_UNKNOWN = 0,
    OBJECT_DRIVER,
    OBJECT_DEVICE,
    OBJECT_DEVICE_NODE,
    OBJECT_VFS_NODE,
    OBJECT_FILE_HANDLE,
    OBJECT_RP,
    OBJECT_DPC,
    OBJECT_TASK,
    OBJECT_SPINLOCK,
    OBJECT_MUTEX,
    OBJECT_SEMAPHORE,
    OBJECT_LOG_HANDLE,
};

#endif