set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_C_COMPILER i686-elf-gcc)
set(CMAKE_CXX_COMPILER i686-elf-g++)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(NABLA_API ${CMAKE_SOURCE_DIR}/../api/nabla)
set(CONFIG_LIBRARIES gcc)
set(CMAKE_ASM_NASM_COMPILER nasm)
set(CMAKE_ASM_NASM_SOURCE_FILE_EXTENSIONS ".asm")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_FLAGS "-masm=intel -ffreestanding -Wall -Wextra -Wsizeof-pointer-memaccess -Wstrict-aliasing -nostdlib -z noexecstack")
set(CMAKE_CXX_FLAGS "-masm=intel -ffreestanding -Wall -Wextra -Wsizeof-pointer-memaccess -Wstrict-aliasing -nostdlib -z noexecstack")
set(CMAKE_ASM_NASM_FLAGS "-f elf32")
set(CMAKE_C_FLAGS_DEBUG "-DDEBUG=1 -g -Og")
set(CMAKE_CXX_FLAGS_DEBUG "-DDEBUG=1 -g -Og")
set(CMAKE_ASM_NASM_FLAGS_DEBUG "-DDEBUG=1 -g -F dwarf")
set(CMAKE_C_FLAGS_RELEASE "-O3")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")