add_library(libc_stdio OBJECT
    asiprintf.c
    asniprintf.c
    asnprintf.c
    asprintf.c
    clearerr_u.c
    clearerr.c
    diprintf.c
    dprintf.c
    fclose.c
    fcloseall.c
    fdopen.c
    feof_u.c
    feof.c
    ferror_u.c
    ferror.c
    fflush_u.c
    fflush.c
    fgetc_u.c
    fgetc.c
    fgetpos.c
    fgets_u.c
    fgets.c
    fgetwc_u.c
    fgetwc.c
    fgetws_u.c
    fgetws.c
    fileno_u.c
    fileno.c
    findfp.c
    fiprintf.c
    fiscanf.c
    flags.c
    fmemopen.c
    fopen.c
    fopencookie.c
    fprintf.c
    fpurge.c
    fputc_u.c
    fputc.c
    fputs_u.c
    fputs.c
    fputwc_u.c
    fputwc.c
    fputws_u.c
    fputws.c
    fread_u.c
    fread.c
    freopen.c
    fscanf.c
    fseek.c
    fseeko.c
    fsetlocking.c
    fsetpos.c
    ftell.c
    ftello.c
    funopen.c
    fvwrite.c
    fwalk.c
    fwide.c
    fwprintf.c
    fwrite_u.c
    fwrite.c
    fwscanf.c
    getc_u.c
    getc.c
    getchar_u.c
    getchar.c
    getdelim.c
    getline.c
    gets.c
    getw.c
    getwc_u.c
    getwc.c
    getwchar_u.c
    getwchar.c
    iprintf.c
    iscanf.c
    makebuf.c
    mktemp.c
    open_memstream.c
    perror.c
    printf.c
    putc_u.c
    putc.c
    putchar_u.c
    putchar.c
    puts.c
    putw.c
    putwchar_u.c
    putwchar.c
    refill.c
    remove.c
    rename.c
    rewind.c
    rget.c
    scanf.c
    sccl.c
    setbuf.c
    setbuffer.c
    setlinebuf.c
    setvbuf.c
    sfputs_r.c
    sfputws_r.c
    siprintf.c
    siscanf.c
    sniprintf.c
    snprintf.c
    sprint_r.c
    sprintf.c
    sscanf.c
    ssprint_r.c
    ssputs_r.c
    ssputws_r.c
    sswprint_r.c
    stdio_ext.c
    stdio.c
    svfiprintf.c
    svfiscanf.c
    svfiwprintf.c
    svfiwscanf.c
    svfprintf.c
    svfscanf.c
    svfwprintf.c
    svfwscanf.c
    swprint_r.c
    swprintf.c
    swscanf.c
    tmpfile.c
    tmpnam.c
    ungetc.c
    ungetwc.c
    vasiprintf.c
    vasniprintf.c
    vasnprintf.c
    vasprintf.c
    vdiprintf.c
    vdprintf.c
    vfiprintf.c
    vfiscanf.c
    vfiwprintf.c
    vfiwscanf.c
    vfprintf.c
    vfscanf.c
    vfwprintf.c
    vfwscanf.c
    viprintf.c
    viscanf.c
    vprintf.c
    vscanf.c
    vsiprintf.c
    vsiscanf.c
    vsniprintf.c
    vsnprintf.c
    vsprintf.c
    vsscanf.c
    vswprintf.c
    vswscanf.c
    vwprintf.c
    vwscanf.c
    wbuf.c
    wbufw.c
    wprintf.c
    wscanf.c
    wsetup.c
)

target_include_directories(libc_stdio PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(libc_stdio PRIVATE libc_includes)