#include "it/wrappers.h"
#include "defines.h"
#include "config.h"
#include <stdint.h>
#include "common.h"
#include "exceptions.h"

#if defined(__i686__)

#include "hal/i686/gdt.h"

#define IDT_FLAG_INTERRUPT_GATE 0xE
#define IDT_FLAG_TRAP_GATE  0xF
#define IDT_FLAG_INTERRUPT_USERMODE 0x60
#define IDT_FLAG_PRESENT 0x80

#define IDT_ENTRY_COUNT 256

/**
 * @brief IDT entry structure
*/
struct IdtEntry
{
	uint16_t isrLow; //lower word of ISR address
	uint16_t selector; //GDT selector for code segment
	uint8_t reserved; //zeros
	uint8_t flags; //attributes
	uint16_t isrHigh; //higher word of ISR address
} PACKED;

/**
 * @brief Interrupt Descriptor Table itself
*/
static struct IdtEntry idt[MAX_CPU_COUNT][IDT_ENTRY_COUNT] ALIGN(8);

/**
 * @brief Insert entry to IDT
 * @param vector Vector number
 * @param *isr Interrupt service routine
 * @return Status code
 */
static STATUS InsertIdtEntry(uint16_t cpu, uint8_t vector, void *isr)
{
    if(vector < IT_FIRST_INTERRUPT_VECTOR)
        return IT_NO_FREE_VECTORS;

    if(cpu >= MAX_CPU_COUNT)
        return OUT_OF_RESOURCES;

    idt[cpu][vector].isrLow = (uint32_t)isr & 0xFFFF;
    idt[cpu][vector].isrHigh = (uint32_t)isr >> 16;
    idt[cpu][vector].selector = GDT_OFFSET(GDT_KERNEL_CS); //interrupt are always processed in kernel mode
    idt[cpu][vector].flags = IDT_FLAG_INTERRUPT_GATE | IDT_FLAG_PRESENT;
    return OK;
}

STATUS I686InstallExceptionHandler(uint16_t cpu, uint8_t vector, void *isr)
{
    if(vector >= IT_FIRST_INTERRUPT_VECTOR)
        return IT_BAD_VECTOR;

    if(cpu >= MAX_CPU_COUNT)
        return OUT_OF_RESOURCES;

    idt[cpu][vector].isrLow = (uint32_t)isr & 0xFFFF;
    idt[cpu][vector].isrHigh = (uint32_t)isr >> 16;
    idt[cpu][vector].selector = GDT_OFFSET(GDT_KERNEL_CS);
    idt[cpu][vector].flags = IDT_FLAG_TRAP_GATE | IDT_FLAG_PRESENT;
    return OK;
}

#endif

#if defined(__i686__) || defined(__amd64__)

STATUS I686InitIdt(void)
{
	CmMemset(idt, 0, sizeof(idt));

	//install exception handlers and wrappers for all non-exception interrupts
    for(uint16_t cpu = 0; cpu < MAX_CPU_COUNT; cpu++)
    {
        I686InstallAllExceptionHandlers(cpu);
        for(uint16_t i = IT_FIRST_INTERRUPT_VECTOR; i < IDT_ENTRY_COUNT; i++)
        {
            InsertIdtEntry(cpu, i, ItWrappers[i - IT_FIRST_INTERRUPT_VECTOR]);
        }
    }

	return OK;
}

void I686InstallIdt(uint16_t cpu)
{
    struct
    {
        uint16_t limit;
        uint32_t base;
    } PACKED idtr;

	//fill IDT register with IDT address and size
	idtr.base = (uintptr_t)idt[cpu];
	idtr.limit = sizeof(struct IdtEntry) * IDT_ENTRY_COUNT - 1;
	//load IDT register address
	ASM("lidt %0" : : "m" (idtr));
	//enable interrupts
	HalEnableInterrupts();
}

void HalDisableInterrupts(void)
{
	ASM("cli");
}

void HalEnableInterrupts(void)
{
	ASM("sti");
}

//interrupt wrappers (functions)
IT_ISR_WRAPPER(32)
IT_ISR_WRAPPER(33)
IT_ISR_WRAPPER(34)
IT_ISR_WRAPPER(35)
IT_ISR_WRAPPER(36)
IT_ISR_WRAPPER(37)
IT_ISR_WRAPPER(38)
IT_ISR_WRAPPER(39)
IT_ISR_WRAPPER(40)
IT_ISR_WRAPPER(41)
IT_ISR_WRAPPER(42)
IT_ISR_WRAPPER(43)
IT_ISR_WRAPPER(44)
IT_ISR_WRAPPER(45)
IT_ISR_WRAPPER(46)
IT_ISR_WRAPPER(47)
IT_ISR_WRAPPER(48)
IT_ISR_WRAPPER(49)
IT_ISR_WRAPPER(50)
IT_ISR_WRAPPER(51)
IT_ISR_WRAPPER(52)
IT_ISR_WRAPPER(53)
IT_ISR_WRAPPER(54)
IT_ISR_WRAPPER(55)
IT_ISR_WRAPPER(56)
IT_ISR_WRAPPER(57)
IT_ISR_WRAPPER(58)
IT_ISR_WRAPPER(59)
IT_ISR_WRAPPER(60)
IT_ISR_WRAPPER(61)
IT_ISR_WRAPPER(62)
IT_ISR_WRAPPER(63)
IT_ISR_WRAPPER(64)
IT_ISR_WRAPPER(65)
IT_ISR_WRAPPER(66)
IT_ISR_WRAPPER(67)
IT_ISR_WRAPPER(68)
IT_ISR_WRAPPER(69)
IT_ISR_WRAPPER(70)
IT_ISR_WRAPPER(71)
IT_ISR_WRAPPER(72)
IT_ISR_WRAPPER(73)
IT_ISR_WRAPPER(74)
IT_ISR_WRAPPER(75)
IT_ISR_WRAPPER(76)
IT_ISR_WRAPPER(77)
IT_ISR_WRAPPER(78)
IT_ISR_WRAPPER(79)
IT_ISR_WRAPPER(80)
IT_ISR_WRAPPER(81)
IT_ISR_WRAPPER(82)
IT_ISR_WRAPPER(83)
IT_ISR_WRAPPER(84)
IT_ISR_WRAPPER(85)
IT_ISR_WRAPPER(86)
IT_ISR_WRAPPER(87)
IT_ISR_WRAPPER(88)
IT_ISR_WRAPPER(89)
IT_ISR_WRAPPER(90)
IT_ISR_WRAPPER(91)
IT_ISR_WRAPPER(92)
IT_ISR_WRAPPER(93)
IT_ISR_WRAPPER(94)
IT_ISR_WRAPPER(95)
IT_ISR_WRAPPER(96)
IT_ISR_WRAPPER(97)
IT_ISR_WRAPPER(98)
IT_ISR_WRAPPER(99)
IT_ISR_WRAPPER(100)
IT_ISR_WRAPPER(101)
IT_ISR_WRAPPER(102)
IT_ISR_WRAPPER(103)
IT_ISR_WRAPPER(104)
IT_ISR_WRAPPER(105)
IT_ISR_WRAPPER(106)
IT_ISR_WRAPPER(107)
IT_ISR_WRAPPER(108)
IT_ISR_WRAPPER(109)
IT_ISR_WRAPPER(110)
IT_ISR_WRAPPER(111)
IT_ISR_WRAPPER(112)
IT_ISR_WRAPPER(113)
IT_ISR_WRAPPER(114)
IT_ISR_WRAPPER(115)
IT_ISR_WRAPPER(116)
IT_ISR_WRAPPER(117)
IT_ISR_WRAPPER(118)
IT_ISR_WRAPPER(119)
IT_ISR_WRAPPER(120)
IT_ISR_WRAPPER(121)
IT_ISR_WRAPPER(122)
IT_ISR_WRAPPER(123)
IT_ISR_WRAPPER(124)
IT_ISR_WRAPPER(125)
IT_ISR_WRAPPER(126)
IT_ISR_WRAPPER(127)
IT_ISR_WRAPPER(128)
IT_ISR_WRAPPER(129)
IT_ISR_WRAPPER(130)
IT_ISR_WRAPPER(131)
IT_ISR_WRAPPER(132)
IT_ISR_WRAPPER(133)
IT_ISR_WRAPPER(134)
IT_ISR_WRAPPER(135)
IT_ISR_WRAPPER(136)
IT_ISR_WRAPPER(137)
IT_ISR_WRAPPER(138)
IT_ISR_WRAPPER(139)
IT_ISR_WRAPPER(140)
IT_ISR_WRAPPER(141)
IT_ISR_WRAPPER(142)
IT_ISR_WRAPPER(143)
IT_ISR_WRAPPER(144)
IT_ISR_WRAPPER(145)
IT_ISR_WRAPPER(146)
IT_ISR_WRAPPER(147)
IT_ISR_WRAPPER(148)
IT_ISR_WRAPPER(149)
IT_ISR_WRAPPER(150)
IT_ISR_WRAPPER(151)
IT_ISR_WRAPPER(152)
IT_ISR_WRAPPER(153)
IT_ISR_WRAPPER(154)
IT_ISR_WRAPPER(155)
IT_ISR_WRAPPER(156)
IT_ISR_WRAPPER(157)
IT_ISR_WRAPPER(158)
IT_ISR_WRAPPER(159)
IT_ISR_WRAPPER(160)
IT_ISR_WRAPPER(161)
IT_ISR_WRAPPER(162)
IT_ISR_WRAPPER(163)
IT_ISR_WRAPPER(164)
IT_ISR_WRAPPER(165)
IT_ISR_WRAPPER(166)
IT_ISR_WRAPPER(167)
IT_ISR_WRAPPER(168)
IT_ISR_WRAPPER(169)
IT_ISR_WRAPPER(170)
IT_ISR_WRAPPER(171)
IT_ISR_WRAPPER(172)
IT_ISR_WRAPPER(173)
IT_ISR_WRAPPER(174)
IT_ISR_WRAPPER(175)
IT_ISR_WRAPPER(176)
IT_ISR_WRAPPER(177)
IT_ISR_WRAPPER(178)
IT_ISR_WRAPPER(179)
IT_ISR_WRAPPER(180)
IT_ISR_WRAPPER(181)
IT_ISR_WRAPPER(182)
IT_ISR_WRAPPER(183)
IT_ISR_WRAPPER(184)
IT_ISR_WRAPPER(185)
IT_ISR_WRAPPER(186)
IT_ISR_WRAPPER(187)
IT_ISR_WRAPPER(188)
IT_ISR_WRAPPER(189)
IT_ISR_WRAPPER(190)
IT_ISR_WRAPPER(191)
IT_ISR_WRAPPER(192)
IT_ISR_WRAPPER(193)
IT_ISR_WRAPPER(194)
IT_ISR_WRAPPER(195)
IT_ISR_WRAPPER(196)
IT_ISR_WRAPPER(197)
IT_ISR_WRAPPER(198)
IT_ISR_WRAPPER(199)
IT_ISR_WRAPPER(200)
IT_ISR_WRAPPER(201)
IT_ISR_WRAPPER(202)
IT_ISR_WRAPPER(203)
IT_ISR_WRAPPER(204)
IT_ISR_WRAPPER(205)
IT_ISR_WRAPPER(206)
IT_ISR_WRAPPER(207)
IT_ISR_WRAPPER(208)
IT_ISR_WRAPPER(209)
IT_ISR_WRAPPER(210)
IT_ISR_WRAPPER(211)
IT_ISR_WRAPPER(212)
IT_ISR_WRAPPER(213)
IT_ISR_WRAPPER(214)
IT_ISR_WRAPPER(215)
IT_ISR_WRAPPER(216)
IT_ISR_WRAPPER(217)
IT_ISR_WRAPPER(218)
IT_ISR_WRAPPER(219)
IT_ISR_WRAPPER(220)
IT_ISR_WRAPPER(221)
IT_ISR_WRAPPER(222)
IT_ISR_WRAPPER(223)
IT_ISR_WRAPPER(224)
IT_ISR_WRAPPER(225)
IT_ISR_WRAPPER(226)
IT_ISR_WRAPPER(227)
IT_ISR_WRAPPER(228)
IT_ISR_WRAPPER(229)
IT_ISR_WRAPPER(230)
IT_ISR_WRAPPER(231)
IT_ISR_WRAPPER(232)
IT_ISR_WRAPPER(233)
IT_ISR_WRAPPER(234)
IT_ISR_WRAPPER(235)
IT_ISR_WRAPPER(236)
IT_ISR_WRAPPER(237)
IT_ISR_WRAPPER(238)
IT_ISR_WRAPPER(239)
IT_ISR_WRAPPER(240)
IT_ISR_WRAPPER(241)
IT_ISR_WRAPPER(242)
IT_ISR_WRAPPER(243)
IT_ISR_WRAPPER(244)
IT_ISR_WRAPPER(245)
IT_ISR_WRAPPER(246)
IT_ISR_WRAPPER(247)
IT_ISR_WRAPPER(248)
IT_ISR_WRAPPER(249)
IT_ISR_WRAPPER(250)
IT_ISR_WRAPPER(251)
IT_ISR_WRAPPER(252)
IT_ISR_WRAPPER(253)
IT_ISR_WRAPPER(254)

/**
 * @brief A table of interrupt wrappers required by the kernel
 */
void (*ItWrappers[IT_HANDLER_COUNT])(void *frame) =
{
    IT_ISR_WRAPPER_NAME(32),
    IT_ISR_WRAPPER_NAME(33),
    IT_ISR_WRAPPER_NAME(34),
    IT_ISR_WRAPPER_NAME(35),
    IT_ISR_WRAPPER_NAME(36),
    IT_ISR_WRAPPER_NAME(37),
    IT_ISR_WRAPPER_NAME(38),
    IT_ISR_WRAPPER_NAME(39),
    IT_ISR_WRAPPER_NAME(40),
    IT_ISR_WRAPPER_NAME(41),
    IT_ISR_WRAPPER_NAME(42),
    IT_ISR_WRAPPER_NAME(43),
    IT_ISR_WRAPPER_NAME(44),
    IT_ISR_WRAPPER_NAME(45),
    IT_ISR_WRAPPER_NAME(46),
    IT_ISR_WRAPPER_NAME(47),
    IT_ISR_WRAPPER_NAME(48),
    IT_ISR_WRAPPER_NAME(49),
    IT_ISR_WRAPPER_NAME(50),
    IT_ISR_WRAPPER_NAME(51),
    IT_ISR_WRAPPER_NAME(52),
    IT_ISR_WRAPPER_NAME(53),
    IT_ISR_WRAPPER_NAME(54),
    IT_ISR_WRAPPER_NAME(55),
    IT_ISR_WRAPPER_NAME(56),
    IT_ISR_WRAPPER_NAME(57),
    IT_ISR_WRAPPER_NAME(58),
    IT_ISR_WRAPPER_NAME(59),
    IT_ISR_WRAPPER_NAME(60),
    IT_ISR_WRAPPER_NAME(61),
    IT_ISR_WRAPPER_NAME(62),
    IT_ISR_WRAPPER_NAME(63),
    IT_ISR_WRAPPER_NAME(64),
    IT_ISR_WRAPPER_NAME(65),
    IT_ISR_WRAPPER_NAME(66),
    IT_ISR_WRAPPER_NAME(67),
    IT_ISR_WRAPPER_NAME(68),
    IT_ISR_WRAPPER_NAME(69),
    IT_ISR_WRAPPER_NAME(70),
    IT_ISR_WRAPPER_NAME(71),
    IT_ISR_WRAPPER_NAME(72),
    IT_ISR_WRAPPER_NAME(73),
    IT_ISR_WRAPPER_NAME(74),
    IT_ISR_WRAPPER_NAME(75),
    IT_ISR_WRAPPER_NAME(76),
    IT_ISR_WRAPPER_NAME(77),
    IT_ISR_WRAPPER_NAME(78),
    IT_ISR_WRAPPER_NAME(79),
    IT_ISR_WRAPPER_NAME(80),
    IT_ISR_WRAPPER_NAME(81),
    IT_ISR_WRAPPER_NAME(82),
    IT_ISR_WRAPPER_NAME(83),
    IT_ISR_WRAPPER_NAME(84),
    IT_ISR_WRAPPER_NAME(85),
    IT_ISR_WRAPPER_NAME(86),
    IT_ISR_WRAPPER_NAME(87),
    IT_ISR_WRAPPER_NAME(88),
    IT_ISR_WRAPPER_NAME(89),
    IT_ISR_WRAPPER_NAME(90),
    IT_ISR_WRAPPER_NAME(91),
    IT_ISR_WRAPPER_NAME(92),
    IT_ISR_WRAPPER_NAME(93),
    IT_ISR_WRAPPER_NAME(94),
    IT_ISR_WRAPPER_NAME(95),
    IT_ISR_WRAPPER_NAME(96),
    IT_ISR_WRAPPER_NAME(97),
    IT_ISR_WRAPPER_NAME(98),
    IT_ISR_WRAPPER_NAME(99),
    IT_ISR_WRAPPER_NAME(100),
    IT_ISR_WRAPPER_NAME(101),
    IT_ISR_WRAPPER_NAME(102),
    IT_ISR_WRAPPER_NAME(103),
    IT_ISR_WRAPPER_NAME(104),
    IT_ISR_WRAPPER_NAME(105),
    IT_ISR_WRAPPER_NAME(106),
    IT_ISR_WRAPPER_NAME(107),
    IT_ISR_WRAPPER_NAME(108),
    IT_ISR_WRAPPER_NAME(109),
    IT_ISR_WRAPPER_NAME(110),
    IT_ISR_WRAPPER_NAME(111),
    IT_ISR_WRAPPER_NAME(112),
    IT_ISR_WRAPPER_NAME(113),
    IT_ISR_WRAPPER_NAME(114),
    IT_ISR_WRAPPER_NAME(115),
    IT_ISR_WRAPPER_NAME(116),
    IT_ISR_WRAPPER_NAME(117),
    IT_ISR_WRAPPER_NAME(118),
    IT_ISR_WRAPPER_NAME(119),
    IT_ISR_WRAPPER_NAME(120),
    IT_ISR_WRAPPER_NAME(121),
    IT_ISR_WRAPPER_NAME(122),
    IT_ISR_WRAPPER_NAME(123),
    IT_ISR_WRAPPER_NAME(124),
    IT_ISR_WRAPPER_NAME(125),
    IT_ISR_WRAPPER_NAME(126),
    IT_ISR_WRAPPER_NAME(127),
    IT_ISR_WRAPPER_NAME(128),
    IT_ISR_WRAPPER_NAME(129),
    IT_ISR_WRAPPER_NAME(130),
    IT_ISR_WRAPPER_NAME(131),
    IT_ISR_WRAPPER_NAME(132),
    IT_ISR_WRAPPER_NAME(133),
    IT_ISR_WRAPPER_NAME(134),
    IT_ISR_WRAPPER_NAME(135),
    IT_ISR_WRAPPER_NAME(136),
    IT_ISR_WRAPPER_NAME(137),
    IT_ISR_WRAPPER_NAME(138),
    IT_ISR_WRAPPER_NAME(139),
    IT_ISR_WRAPPER_NAME(140),
    IT_ISR_WRAPPER_NAME(141),
    IT_ISR_WRAPPER_NAME(142),
    IT_ISR_WRAPPER_NAME(143),
    IT_ISR_WRAPPER_NAME(144),
    IT_ISR_WRAPPER_NAME(145),
    IT_ISR_WRAPPER_NAME(146),
    IT_ISR_WRAPPER_NAME(147),
    IT_ISR_WRAPPER_NAME(148),
    IT_ISR_WRAPPER_NAME(149),
    IT_ISR_WRAPPER_NAME(150),
    IT_ISR_WRAPPER_NAME(151),
    IT_ISR_WRAPPER_NAME(152),
    IT_ISR_WRAPPER_NAME(153),
    IT_ISR_WRAPPER_NAME(154),
    IT_ISR_WRAPPER_NAME(155),
    IT_ISR_WRAPPER_NAME(156),
    IT_ISR_WRAPPER_NAME(157),
    IT_ISR_WRAPPER_NAME(158),
    IT_ISR_WRAPPER_NAME(159),
    IT_ISR_WRAPPER_NAME(160),
    IT_ISR_WRAPPER_NAME(161),
    IT_ISR_WRAPPER_NAME(162),
    IT_ISR_WRAPPER_NAME(163),
    IT_ISR_WRAPPER_NAME(164),
    IT_ISR_WRAPPER_NAME(165),
    IT_ISR_WRAPPER_NAME(166),
    IT_ISR_WRAPPER_NAME(167),
    IT_ISR_WRAPPER_NAME(168),
    IT_ISR_WRAPPER_NAME(169),
    IT_ISR_WRAPPER_NAME(170),
    IT_ISR_WRAPPER_NAME(171),
    IT_ISR_WRAPPER_NAME(172),
    IT_ISR_WRAPPER_NAME(173),
    IT_ISR_WRAPPER_NAME(174),
    IT_ISR_WRAPPER_NAME(175),
    IT_ISR_WRAPPER_NAME(176),
    IT_ISR_WRAPPER_NAME(177),
    IT_ISR_WRAPPER_NAME(178),
    IT_ISR_WRAPPER_NAME(179),
    IT_ISR_WRAPPER_NAME(180),
    IT_ISR_WRAPPER_NAME(181),
    IT_ISR_WRAPPER_NAME(182),
    IT_ISR_WRAPPER_NAME(183),
    IT_ISR_WRAPPER_NAME(184),
    IT_ISR_WRAPPER_NAME(185),
    IT_ISR_WRAPPER_NAME(186),
    IT_ISR_WRAPPER_NAME(187),
    IT_ISR_WRAPPER_NAME(188),
    IT_ISR_WRAPPER_NAME(189),
    IT_ISR_WRAPPER_NAME(190),
    IT_ISR_WRAPPER_NAME(191),
    IT_ISR_WRAPPER_NAME(192),
    IT_ISR_WRAPPER_NAME(193),
    IT_ISR_WRAPPER_NAME(194),
    IT_ISR_WRAPPER_NAME(195),
    IT_ISR_WRAPPER_NAME(196),
    IT_ISR_WRAPPER_NAME(197),
    IT_ISR_WRAPPER_NAME(198),
    IT_ISR_WRAPPER_NAME(199),
    IT_ISR_WRAPPER_NAME(200),
    IT_ISR_WRAPPER_NAME(201),
    IT_ISR_WRAPPER_NAME(202),
    IT_ISR_WRAPPER_NAME(203),
    IT_ISR_WRAPPER_NAME(204),
    IT_ISR_WRAPPER_NAME(205),
    IT_ISR_WRAPPER_NAME(206),
    IT_ISR_WRAPPER_NAME(207),
    IT_ISR_WRAPPER_NAME(208),
    IT_ISR_WRAPPER_NAME(209),
    IT_ISR_WRAPPER_NAME(210),
    IT_ISR_WRAPPER_NAME(211),
    IT_ISR_WRAPPER_NAME(212),
    IT_ISR_WRAPPER_NAME(213),
    IT_ISR_WRAPPER_NAME(214),
    IT_ISR_WRAPPER_NAME(215),
    IT_ISR_WRAPPER_NAME(216),
    IT_ISR_WRAPPER_NAME(217),
    IT_ISR_WRAPPER_NAME(218),
    IT_ISR_WRAPPER_NAME(219),
    IT_ISR_WRAPPER_NAME(220),
    IT_ISR_WRAPPER_NAME(221),
    IT_ISR_WRAPPER_NAME(222),
    IT_ISR_WRAPPER_NAME(223),
    IT_ISR_WRAPPER_NAME(224),
    IT_ISR_WRAPPER_NAME(225),
    IT_ISR_WRAPPER_NAME(226),
    IT_ISR_WRAPPER_NAME(227),
    IT_ISR_WRAPPER_NAME(228),
    IT_ISR_WRAPPER_NAME(229),
    IT_ISR_WRAPPER_NAME(230),
    IT_ISR_WRAPPER_NAME(231),
    IT_ISR_WRAPPER_NAME(232),
    IT_ISR_WRAPPER_NAME(233),
    IT_ISR_WRAPPER_NAME(234),
    IT_ISR_WRAPPER_NAME(235),
    IT_ISR_WRAPPER_NAME(236),
    IT_ISR_WRAPPER_NAME(237),
    IT_ISR_WRAPPER_NAME(238),
    IT_ISR_WRAPPER_NAME(239),
    IT_ISR_WRAPPER_NAME(240),
    IT_ISR_WRAPPER_NAME(241),
    IT_ISR_WRAPPER_NAME(242),
    IT_ISR_WRAPPER_NAME(243),
    IT_ISR_WRAPPER_NAME(244),
    IT_ISR_WRAPPER_NAME(245),
    IT_ISR_WRAPPER_NAME(246),
    IT_ISR_WRAPPER_NAME(247),
    IT_ISR_WRAPPER_NAME(248),
    IT_ISR_WRAPPER_NAME(249),
    IT_ISR_WRAPPER_NAME(250),
    IT_ISR_WRAPPER_NAME(251),
    IT_ISR_WRAPPER_NAME(252),
    IT_ISR_WRAPPER_NAME(253),
    IT_ISR_WRAPPER_NAME(254),
}
;


#endif