//This header file is generated automatically
#ifndef EXPORTED_KERNEL_H_
#define EXPORTED_KERNEL_H_

#ifdef __cplusplus
extern "C" 
{
#endif

#include "assert.h"
#include "color.h"
#include "common.h"
#include "defines.h"
#include "arch/i686/i686.h"
#include "common/stdio.h"
#include "ddk/stor.h"
#include "ex/elf.h"
#include "ex/exec.h"
#include "ex/kdrv.h"
#include "ex/ksym.h"
#include "ex/load.h"
#include "hal/cpu.h"
#include "hal/hal.h"
#include "hal/interrupt.h"
#include "hal/ioport.h"
#include "hal/time.h"
#include "io/dev/dev.h"
#include "io/dev/enumeration.h"
#include "io/dev/res.h"
#include "io/dev/rp.h"
#include "io/dev/typedefs.h"
#include "io/dev/types.h"
#include "io/dev/vol.h"
#include "io/disp/print.h"
#include "io/fs/devfs.h"
#include "io/fs/fs.h"
#include "io/fs/fstypedefs.h"
#include "io/fs/mount.h"
#include "io/fs/taskfs.h"
#include "io/fs/vfs.h"
#include "io/log/syslog.h"
#include "it/it.h"
#include "it/wrappers.h"
#include "it/handlers/bound.h"
#include "it/handlers/dfault.h"
#include "it/handlers/divzero.h"
#include "it/handlers/fpufaults.h"
#include "it/handlers/gp.h"
#include "it/handlers/nmi.h"
#include "it/handlers/pagefault.h"
#include "it/handlers/traps.h"
#include "it/handlers/ud.h"
#include "ke/core/dpc.h"
#include "ke/core/mutex.h"
#include "ke/core/panic.h"
#include "ke/sched/idle.h"
#include "ke/sched/sched.h"
#include "ke/sched/sleep.h"
#include "ke/task/task.h"
#include "ke/task/tss.h"
#include "mm/avl.h"
#include "mm/dynmap.h"
#include "mm/gdt.h"
#include "mm/heap.h"
#include "mm/mm.h"
#include "mm/mmio.h"
#include "mm/palloc.h"
#include "mm/valloc.h"
#include "sdrv/acpi.h"
#include "sdrv/dcpuid.h"
#include "sdrv/fpu.h"
#include "sdrv/ioapic.h"
#include "sdrv/lapic.h"
#include "sdrv/mp.h"
#include "sdrv/msr.h"
#include "sdrv/pic.h"
#include "sdrv/pit.h"
#include "sdrv/sse.h"
#include "sdrv/tsc.h"
#include "sdrv/bootvga/bootvga.h"
#include "sdrv/bootvga/font.h"
#include "sdrv/initrd/initrd.h"

#ifdef __cplusplus
}
#endif

#endif